image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker info

build:
  stage: build
  script:
    - echo "Building the application"
    - docker build -t my-app .

test:
  stage: test
  script:
    - npm test


