      
stages:
  
  - build
  - build_image
  - test

cache:
  paths:
    - node_modules/

variables:
  NODE_ENV: 'development'
  DOCKER_DRIVER: overlay2


build_application:
  image: node:14
  stage: build
  script:
    - echo "Building the application"
    - npm run build
  artifacts:
    paths:
      - dist/


build_image:
  image: docker:latest

  services:
  - docker:dind

  stage: build
  
  script:
    #- docker build -t app_js .
    #- docker tag app_js $CI_REGISTRY_IMAGE:latest
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
    
  only:
    - main

test_application:
  stage: test
  script:
    - echo "Running tests"
    - docker run app_js npm test

  only:
   - main