image: node:14

stages:
  
  - build
  - test

cache:
  paths:
    - node_modules/

variables:
  NODE_ENV: 'development'


build_application:
  stage: build
  script:
    - echo "Building the application"
    - npm run build
  artifacts:
    paths:
      - dist/

test_application:
  stage: test
  script:
    - echo "Running tests"
    - npm test
