image: node:14

stages:
  - install
  - build
  - test

cache:
  paths:
    - node_modules/

variables:
  NODE_ENV: 'development'

install_dependencies:
  stage: install
  script:
    - echo "Installing dependencies"
    - npm install
  artifacts:
    paths:
      - node_modules/

build_application:
  stage: build
  script:
    - echo "Building the application"
    - npm run build
  artifacts:
    paths:
      - dist/

test_application:
  stage: test
  script:
    - echo "Running tests"
    - npm test
