image: node:14

stages:
  - build
  - test

variables:
  NODE_ENV: 'development'

cache:
  paths:
    - node_modules/

before_script:
  - npm install

build:
  stage: build
  script:
    - echo "Building the application"
    - npm run build
    
test:
  stage: test
  script:
    - npm test
